clusters = local, redpanda

local.bootstrap.servers = kafka:9092
local.security.protocol = PLAINTEXT

redpanda.bootstrap.servers = d6sinugbmgg6innos300.any.eu-central-1.mpx.prd.cloud.redpanda.com:9092
redpanda.security.protocol = SASL_SSL
redpanda.sasl.mechanism = SCRAM-SHA-256
redpanda.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="energy-compliance-user" password="energypass123";

local->redpanda.enabled = true
redpanda->local.enabled = false

local->redpanda.topics = energy\.public\.facilities,energy\.public\.meter_readings,energy\.public\.investments
local->redpanda.emit.heartbeats.enabled = false
local->redpanda.emit.checkpoints.enabled = false

# local->redpanda worker uses local Kafka as backing store
local->redpanda.config.storage.topic = mm2-configs.local.internal
local->redpanda.offset.storage.topic = mm2-offsets.local.internal
local->redpanda.status.storage.topic = mm2-status.local.internal

# redpanda->local worker also uses local Kafka as backing store
redpanda->local.config.storage.topic = mm2-configs.local.internal
redpanda->local.offset.storage.topic = mm2-offsets.local.internal
redpanda->local.status.storage.topic = mm2-status.local.internal

config.storage.replication.factor = 1
offset.storage.replication.factor = 1
status.storage.replication.factor = 1

replication.factor = 3
checkpoints.topic.replication.factor = 3
heartbeats.topic.replication.factor = 3
offset-syncs.topic.replication.factor = 3
