bootstrap.servers=kafka:9092
group.id=energy-connect-group
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.storage.topic=energy_connect_offsets
offset.storage.replication.factor=1
config.storage.topic=energy_connect_configs
config.storage.replication.factor=1
status.storage.topic=energy_connect_status
status.storage.replication.factor=1
offset.flush.interval.ms=10000
plugin.path=/kafka/connect
security.protocol=PLAINTEXT
producer.security.protocol=SASL_SSL
producer.sasl.mechanism=SCRAM-SHA-256
producer.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${REDPANDA_USERNAME}" password="${REDPANDA_PASSWORD}";
consumer.security.protocol=SASL_SSL
consumer.sasl.mechanism=SCRAM-SHA-256
consumer.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${REDPANDA_USERNAME}" password="${REDPANDA_PASSWORD}";
